version: "3.3"

services:
  server:
    image: nginx:1.21-alpine
    command: nginx -g "daemon off;"
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf.d/:/etc/nginx/conf.d/
      - ./public:/usr/share/nginx/html/public
      - ./src:/usr/share/nginx/html/src
      - ./composer.json:/usr/share/nginx/html/composer.json
      - ./composer.lock:/usr/share/nginx/html/composer.lock
      - ./vendor:/usr/share/nginx/html/vendor
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: joseluisq/php-fpm:8.1
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9090"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    expose:
      - "9090"
    volumes:
      - ./public:/usr/share/nginx/html/public
      - ./src:/usr/share/nginx/html/src
      - ./composer.json:/usr/share/nginx/html/composer.json
      - ./composer.lock:/usr/share/nginx/html/composer.lock
      - ./vendor:/usr/share/nginx/html/vendor
