version: "3.3"

services:
  server:
    image: nginx:1.21-alpine
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf.d/:/etc/nginx/conf.d/
      - ./:/usr/share/nginx/html
    depends_on:
      - php-fpm
    links:
      - php-fpm

  php-fpm:
    image: joseluisq/php-fpm:8.1
    env_file:
      - .env
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9090"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    expose:
      - "9090"
    volumes:
      - ./:/usr/share/nginx/html
      # - ../leap:/usr/share/nginx/leap
      # - ../ruta:/usr/share/nginx/ruta

  # Composer for development
  ##########################
  # "repositories": [
  #     {
  #         "type": "path",
  #         "url": "../leap"
  #     },
  #     {
  #         "type": "path",
  #         "url": "../ruta"
  #     }
  # ],
